
spring:
  application:
    name: blockAndPoll

  datasource:
    url: jdbc:postgresql://localhost:5432/algoproject
    username: postgres
    password: developer
    max-connections: 10

server.port: ${PORT:5000}

logging:
  level:
    org:
      springframework:
        web: ERROR